@startuml
title High-Level Design Methodology

start

:System Requirements;

:Architecture Definition;

:Model in SystemC;

:Functional Validation;

if (Architecture OK?) then (Yes)

:Implement Compute Units in HLS;

:Generate RTL;

:Synthesize in FPGA;

:Execute Benchmarks;

else (No)

:Modify Architecture;

-back->

endif

stop

@enduml