// ptx_parser.h — PTX subset lexer + parser
//
// Parses a PTX text (as generated by nvcc --ptx with .address_size 32) into
// a simple AST used by RvEmitter.  Only the MVP instruction subset needed for
// vector_add / saxpy-style kernels is supported.
//
// MVP PTX subset:
//   .reg .pred %p<N>; .reg .u32 %r<N>; .reg .f32 %f<N>; .reg .b64 %rd<N>
//   ld.param.u32/.f32/.u64   ld.global.u32/.f32/.u64
//   st.global.u32/.f32
//   mov.u32  (including special regs %tid.x/y/z, %ctaid.x/y/z, %ntid.x/y/z)
//   add/sub/mul.lo/mul.wide/mad.lo/shl  (.u32/.s32/.u64/.b32)
//   add/sub/mul/fma.rn/div (.f32)
//   setp.lt/le/gt/ge/eq/ne  (.u32/.s32/.f32)
//   cvta.to.global.u64   cvt   @%p bra   @!%p bra   bra   ret

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace riscv_gpgpu {
namespace ptx {

// ── Operand ────────────────────────────────────────────────────────────────────

struct PtxOperand {
    enum class Kind {
        Reg,        // %r0, %f0, %p0, %rd0
        SpecialReg, // %tid.x, %ctaid.y, %ntid.z, ...
        IntImm,     // integer literal
        FltImm,     // float literal
        Label,      // $L__xxx (branch target)
        MemRef      // [%r0], [%r0+N], [param_name]
    } kind = Kind::IntImm;

    std::string name;       // register / special reg / label name (without % / $)
    int64_t     int_val  = 0;
    double      flt_val  = 0.0;
    // MemRef fields
    std::string mem_base;       // register name (without %) or empty if param_ref
    std::string param_name;     // non-empty if MemRef is [param_name]
    int64_t     mem_offset = 0;
};

// ── Declarations ────────────────────────────────────────────────────────────────

struct PtxParam {
    std::string space;   // ".u32", ".f32", ".u64", ".b32", ".b64", ".b8"
    std::string name;    // "param_0", "saxpy_param_0", etc.
    uint32_t    index = 0;
};

struct PtxRegDecl {
    std::string prefix;  // "%r", "%f", "%p", "%rd"
    std::string type;    // "u32", "f32", "pred", "b32", "b64"
    uint32_t    count = 0;
};

// ── Instruction ─────────────────────────────────────────────────────────────────

struct PtxInstr {
    std::string label;      // non-empty → this is a label definition ("L__xxx")
    std::string pred;       // predicate register name without %, e.g. "p0"; empty if none
    bool        pred_not = false; // @!%p vs @%p
    std::string op;         // full opcode, e.g. "ld.global.u32", "setp.ge.u32"
    std::vector<PtxOperand> operands;
};

// ── Kernel AST ──────────────────────────────────────────────────────────────────

struct PtxKernel {
    std::string              name;       // kernel function name
    std::vector<PtxParam>    params;
    std::vector<PtxRegDecl>  reg_decls;
    std::vector<PtxInstr>    body;       // includes label pseudo-instructions
};

// ── Parser ──────────────────────────────────────────────────────────────────────

class PtxParser {
public:
    // Parse the first .entry kernel found in ptx_text.
    // Returns a PtxKernel with name=="" on error.
    PtxKernel parse(const std::string& ptx_text);

    const std::string& lastError() const { return error_; }

private:
    std::string error_;

    // Tokenizer state
    const char* src_  = nullptr;
    size_t      pos_  = 0;
    size_t      len_  = 0;

    // Token types
    enum class TK {
        WORD,         // identifier or dot-prefixed keyword or opcode
        PERCENT,      // %word  (register / special reg)
        DOLLAR,       // $word  (label reference)
        INT,          // integer literal
        FLOAT,        // float literal
        LPAREN, RPAREN,
        LBRACE, RBRACE,
        LANGLE, RANGLE,
        LBRACKET, RBRACKET,
        COMMA, SEMICOLON, COLON,
        AT, BANG, PLUS, MINUS,
        END
    };

    struct Token {
        TK          type;
        std::string text;
        int64_t     ival = 0;
        double      fval = 0.0;
    };

    void    skipWhitespaceAndComments();
    Token   nextToken();
    Token   peekToken();
    bool    expect(TK type, const std::string& hint = "");

    std::vector<Token> tokens_;
    size_t             tok_pos_ = 0;

    void tokenize(const std::string& text);
    Token cur()  { return tok_pos_ < tokens_.size() ? tokens_[tok_pos_] : Token{TK::END}; }
    Token peek(size_t ahead = 1) { size_t p = tok_pos_ + ahead; return p < tokens_.size() ? tokens_[p] : Token{TK::END}; }
    void  advance() { if (tok_pos_ < tokens_.size()) ++tok_pos_; }

    bool parseKernel(PtxKernel& out);
    bool parseParams(std::vector<PtxParam>& out);
    bool parseBody(PtxKernel& k);
    bool parseRegDecl(PtxKernel& k);
    bool parseInstr(PtxInstr& out);
    PtxOperand parseOperand();
    PtxOperand parseMemRef();
};

} // namespace ptx
} // namespace riscv_gpgpu
