function wfm = newBluetoothWaveform(mode, phyVariant, configObject, samples, sampleRate, payloadBits, sourceReference)
%newBluetoothWaveform Construct a validated BluetoothWaveform struct (data-model.md)
%   Enforces the field shapes and validation rules from
%   docs/001-bluetooth-link-simulation/data-model.md: mode must be "BREDR" or
%   "LE", and samples must be non-empty (FR-001/FR-002/FR-010).

mode = string(mode);
if ~ismember(mode, ["BREDR", "LE"])
    error("newBluetoothWaveform:InvalidMode", ...
        'mode must be "BREDR" or "LE", got "%s".', mode);
end
if isempty(samples)
    error("newBluetoothWaveform:EmptySamples", ...
        "samples must be non-empty and produced by a toolbox generator function (FR-010).");
end

wfm = struct( ...
    'mode', mode, ...
    'phyVariant', string(phyVariant), ...
    'configObject', configObject, ...
    'samples', samples, ...
    'sampleRate', sampleRate, ...
    'payloadBits', int8(payloadBits(:)), ...
    'sourceReference', string(sourceReference));

end
